name: tzkt
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  intersperse: ^2.0.0
  page_transition: ^2.1.0
  dio: ^5.4.3+1
  logger: ^2.3.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.7.0
  google_fonts: ^6.2.1

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.1.7
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/assets/
  line_length: 80

  integrations:
    flutter_svg: true
    json: true

  assets:
    enabled: true
    outputs:
      class_name: TzktAssets

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/svg/
    - assets/images/png/
